[versions]
lombok = "1.18.42"
picocli = "4.7.7"
resilience4j = "2.3.0"
log-api = "2.25.3"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
resilience4j-retry = { module = "io.github.resilience4j:resilience4j-retry", version.ref = "resilience4j" }
log4j-api = {module = "org.apache.logging.log4j:log4j-api", version.ref = "log-api"}
log4j-core = {module = "org.apache.logging.log4j:log4j-core", version.ref = "log-api"}